basePath: /v1
definitions:
  utils.Result:
    properties:
      data: {}
      msg:
        type: string
      rc:
        type: integer
    type: object
info:
  contact: {}
  description: Gin API 基础工程
  title: Test API
  version: v1
paths:
  /login:
    post:
      description: 登入
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
        "403":
          description: Forbidden
          schema:
            type: user
      summary: 登入
      tags:
      - 登入
  /media:
    get:
      description: 获取所有媒体
      parameters:
      - description: 登入后返回的token
        in: header
        name: token
        required: true
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 获取所有媒体
      tags:
      - 媒体相关
  /media/{id}:
    delete:
      description: 删除文件
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 文件ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 删除文件
      tags:
      - 媒体相关
    get:
      description: 通过id获取文件
      parameters:
      - description: 登入后返回的token
        in: header
        name: token
        required: true
        type: string
      - description: The key for staticblock
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 通过id获取文件
      tags:
      - 媒体相关
  /register:
    post:
      description: 注册
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
        "403":
          description: Forbidden
          schema:
            type: user
      summary: 注册
      tags:
      - 注册
  /upload:
    post:
      description: 上传
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 上传
      tags:
      - 媒体相关
  /user:
    get:
      description: 获取所有用户
      parameters:
      - description: 登入后返回的token
        in: header
        name: token
        required: true
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 获取所有用户
      tags:
      - 用户相关
    post:
      description: 添加用户
      parameters:
      - description: 登入后返回的token
        in: header
        name: token
        required: true
        type: string
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 添加用户
      tags:
      - 用户相关
  /user/{id}:
    delete:
      description: 删除用户
      parameters:
      - description: 登入后返回的token
        in: header
        name: token
        required: true
        type: string
      - description: The uid you want to delete
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 删除用户
      tags:
      - 用户相关
    get:
      description: 通过id获取用户
      parameters:
      - description: 登入后返回的token
        in: header
        name: token
        required: true
        type: string
      - description: The key for staticblock
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 通过id获取用户
      tags:
      - 用户相关
    put:
      description: 更新用户
      parameters:
      - description: 登入后返回的token
        in: header
        name: token
        required: true
        type: string
      - description: The uid you want to update
        in: path
        name: id
        required: true
        type: integer
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 更新用户
      tags:
      - 用户相关
swagger: "2.0"
